export const ADD_TAG = 'ADD_TAG'
export const REMOVE_TAG = 'REMOVE_TAG'

export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS'
export const FETCH_INGREDIENTS_FAILURE = 'FETCH_INGREDIENTS_FAILURE'

export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS'
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE'

export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS'
export const FETCH_RECIPE_FAILURE = 'FETCH_RECIPE_FAILURE'