export const ADD_TAG = 'ADD_TAG'
export const REMOVE_TAG = 'REMOVE_TAG'

export const FETCH_INGREDIENTS_BEGIN   = 'FETCH_INGREDIENTS_BEGIN'
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS'
export const FETCH_INGREDIENTS_FAILURE = 'FETCH_INGREDIENTS_FAILURE'

export const FETCH_RECIPES_BEGIN   = 'FETCH_RECIPES_BEGIN'
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS'
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE'